import 'package:get/get.dart';
class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
     //ENGLISH LANGUAGE
    'en_US':{
      'Full name':'Full name',
      'School Number (Optional)':'School Number (Optional)',
      'Mudar idioma':'Change Language',
       'Phone number (Optional)':'Phone number (Optional)',
       'Save':'Save',
       'Pesquise um alimento': 'Search for a food',
       'Os Nossos Produtos': 'Our products',
       'Tomate Cherry Semente': 'Cherry Tomato Seed',
       'Alface (Tipo) Semente': 'Lettuce (Type) Seed',
       'Cenoura (Tipo) Semente': 'Carrot seed (type)',
       'Alface': 'Lettuce',
       'Descrição': 'Description',
      'A alface é uma planta herbácea, com um': 'Lettuce is a herbaceous plant, with a',
      'caule diminuto ao qual se prendem as folhas.': 'tiny stem to which the leaves attach.',
      'Estas são a parte comestível da planta e': 'These are the edible part of the plant and',
      'podem ser lisas ou crespas, fechando-se ou':'they can be smooth or curly, closing or',
      'não na forma de uma "cabeça". A coloração': 'not in the form of a "head". the coloring',
      'das plantas pode variar do verde-amarelado': 'of the plants can vary from yellowish-green',
      'até o verde escuro e também pode ser roxa': 'up to dark green and can also be purple',
      'dependendo da colheita.': 'depending on the grow crops.',
      'Plantação': 'Plantation',
'Plante as sementes com 1/8 a 1/4 de polegada': 'Plant the seeds 1/8 to 1/4 inch',
'de profundidade. As sementes de alface': 'deep. The Lettuce Seeds',
'precisam de luz para germinar, por isso não as': 'they need light to germinate, so don`t them',
'semeie muito fundo. As sementes podem ser': 'sow very deep. The seeds can be',
'semeadas em fileiras únicas ou a lanço para': 'sown in single rows or tossed to',
'plantio em fileiras largas (variedades de folhas': 'planting in wide rows (leaf varieties',
'soltas são as melhores para isso). Ao': 'loose are best for this). To',
'transmitir, desbaste mudas de 1 a 2 polegadas': 'broadcast, thinning 1- to 2-inch seedlings',
'de altura para obter o espaçamento adequado.':'tall to get proper spacing.',      
      'Preço Total': 'Total price',
      'Login': 'Login',
      'email': 'email',
      'nome@email.com':'name@email.com',
       'Digite o seu email!': 'Enter your email!',
       'password': 'password',
       'Digite a sua senha': 'Type your password',
       'Digite a sua senha!': 'Type your password!',
       'Digite uma senha mais forte!': 'Enter a stronger password!',
       'Esqueceu a Palavra-Passe?': 'Forgot Password?',
        'Want to create an account?':  'Want to create an account?',
        'Register': "Register",
        'Produtos': 'Products',
        'Explore a nossa variedade de produtos': 'Explore our range of products',
        'Costumização': 'Customization',
        'Customize o seu próprio perfil e guarde os seus momentos especiais': 'Customize your own profile and save your special moments',
        'Jardim': 'Garden',
        'Esteja a par do crescimento dos seus alimentos com o nosso menu “Jardim”': 'Keep in touch with the growth of your food with our “Garden” menu',
        'Next':  'Next',
        'Pic Image From': 'Pic Image From',
        'CAMERA': 'CAMERA',
        'GALLERY': 'GALLERY',
        'CANCEL': 'CANCEL',
        'O seu Perfil': 'Your Profile',
        'Adicionar Foto': 'Add Photo',
        'Nome': 'Name',
        'Insira o seu nome': 'Enter your name',
        'Digite o seu nome!': 'Type your name!',
        'Número Escola (Opcional)': 'School Number (Optional)',
        'Insira o seu número da escola': 'Enter your school number'
        
        
    },
     //PORTUGUESE LANGUAGE
    'pt_BR':{
      'Full name': 'Nome completo',
      'School Number (Optional)':'Número de Escola (Opcional)',
      'Mudar idioma':'Mudar idioma',
      'Phone number (Optional)':'Número de telefone (Opcional)',
      'Save':'Salvar',
      'Pesquise um alimento': 'Pesquise um alimento',
      'Os Nossos Produtos': 'Os Nossos Produtos',
      'Tomate Cherry Semente': 'Tomate Cherry Semente',
      'Alface (Tipo) Semente': 'Alface (Tipo) Semente',
      'Cenoura (Tipo) Semente': 'Cenoura (Tipo) Semente',
      'Alface': 'Alface',
      'Descrição': 'Descrição',
     'A alface é uma planta herbácea, com um': 'A alface é uma planta herbácea, com um',
      'caule diminuto ao qual se prendem as folhas.': 'caule diminuto ao qual se prendem as folhas.',
      'Estas são a parte comestível da planta e':  'Estas são a parte comestível da planta e',
      'podem ser lisas ou crespas, fechando-se ou':'podem ser lisas ou crespas, fechando-se ou',
      'não na forma de uma "cabeça". A coloração': 'não na forma de uma "cabeça". A coloração',
      'das plantas pode variar do verde-amarelado': 'das plantas pode variar do verde-amarelado',
      'até o verde escuro e também pode ser roxa': 'até o verde escuro e também pode ser roxa',
      'dependendo da colheita.': 'dependendo da colheita.',
      'Plantação': 'Plantação',  
'Plante as sementes com 1/8 a 1/4 de polegada': 'Plante as sementes com 1/8 a 1/4 de polegada',
'de profundidade. As sementes de alface': 'de profundidade. As sementes de alface',
'precisam de luz para germinar, por isso não as': 'precisam de luz para germinar, por isso não as',
'semeie muito fundo. As sementes podem ser': 'semeie muito fundo. As sementes podem ser',
'semeadas em fileiras únicas ou a lanço para': 'semeadas em fileiras únicas ou a lanço para',
'plantio em fileiras largas (variedades de folhas': 'plantio em fileiras largas (variedades de folhas',
'soltas são as melhores para isso). Ao': 'soltas são as melhores para isso). Ao',
'transmitir, desbaste mudas de 1 a 2 polegadas': 'transmitir, desbaste mudas de 1 a 2 polegadas',
'de altura para obter o espaçamento adequado.':'de altura para obter o espaçamento adequado.',
      'Preço Total': 'Preço Total',
      'Login': 'Entrar',
      'email': 'email',
      'nome@email.com':'nome@email.com',
      'Digite o seu email!': 'Digite o seu email!',
      'password': 'senha',
      'Digite a sua senha': 'Digite a sua senha',
      'Digite a sua senha!': 'Digite a sua senha!',
      'Digite uma senha mais forte!':'Digite uma senha mais forte!',
       'Esqueceu a Palavra-Passe?': 'Esqueceu a Palavra-Passe?',
       'Want to create an account?': 'Quer criar uma conta?',
        'Register': "Registro",
        'Produtos': 'Produtos',
       'Explore a nossa variedade de produtos': 'Explore a nossa variedade de produtos',
       'Costumização': 'Costumização',
         'Customize o seu próprio perfil e guarde os seus momentos especiais': 'Customize o seu próprio perfil e guarde os seus momentos especiais',
         'Jardim': 'Jardim',
         'Esteja a par do crescimento dos seus alimentos com o nosso menu “Jardim”': 'Esteja a par do crescimento dos seus alimentos com o nosso menu “Jardim”',
           'Next': 'Próximo',
           'Pic Image From': 'Escolher imagem a partir da',
           'CAMERA': 'CÂMERA',
           'GALLERY': 'GALERIA',
           'CANCEL': 'CANCELAR',
           'O seu Perfil': 'O seu Perfil',
           'Adicionar Foto': 'Adicionar Foto',
           'Nome':'Nome',
           'Insira o seu nome': 'Insira o seu nome',
           'Digite o seu nome!': 'Digite o seu nome!',
           'Número Escola (Opcional)': 'Número Escola (Opcional)',
            'Insira o seu número da escola': 'Insira o seu número da escola'

  
    },
    //SPANISH LANGUAGE
    'es_ES':{
      'Full name': 'Nombre completo',
      'School Number (Optional)':'Número de escuela (Opcional)',
      'Mudar idioma':'Cambiar idioma',
       'Phone number (Optional)':'Número de teléfono (Opcional)',
       'Save':'Guardar',
       'Pesquise um alimento': 'Buscar una comida',
       'Os Nossos Produtos': 'Nuestros productos',
       'Tomate Cherry Semente': 'Semilla de Tomate Cherry',
       'Alface (Tipo) Semente': 'Semilla de Lechuga (Tipo)',
       'Cenoura (Tipo) Semente': 'Zanahoria (Tipo) Semilla',
       'Alface': 'Lechuga',
       'Descrição': 'Descripción',
       'A alface é uma planta herbácea, com um': 'La lechuga es una planta herbácea, con un',
      'caule diminuto ao qual se prendem as folhas.': 'pequeño tallo al que se unen las hojas.',
      'Estas são a parte comestível da planta e':  'Estos son la parte comestible de la planta y',
      'podem ser lisas ou crespas, fechando-se ou':'pueden ser lisos o rizados, cerrando o',
      'não na forma de uma "cabeça". A coloração': 'no en la forma de una "cabeza". el colorante',
      'das plantas pode variar do verde-amarelado': 'de las plantas puede variar de verde amarillento',
      'até o verde escuro e também pode ser roxa': 'hasta verde oscuro y también puede ser púrpura',
      'dependendo da colheita.': 'dependiendo de la cosecha.',       
       'Plantação': 'Plantación',
'Plante as sementes com 1/8 a 1/4 de polegada': 'Plante las semillas de 1/8 a 1/4 de pulgada',
'de profundidade. As sementes de alface': 'profundo. Las semillas de lechuga',
'precisam de luz para germinar, por isso não as': 'necesitan luz para germinar, así que ellos no',
'semeie muito fundo. As sementes podem ser': 'sembrar muy profundo. Las semillas pueden ser',
'semeadas em fileiras únicas ou a lanço para': 'sembrado en hileras individuales o arrojado a',
'plantio em fileiras largas (variedades de folhas': 'plantar en hileras anchas (variedades de hojas',
'soltas são as melhores para isso). Ao': 'sueltos son mejores para esto). A',
'transmitir, desbaste mudas de 1 a 2 polegadas': 'difusión, adelgazamiento de plántulas de 1 a 2 pulgadas',
'de altura para obter o espaçamento adequado.':'alto para obtener el espacio adecuado.',
       'Preço Total': 'Precio total',
       'Login': 'Acceso',
       'email': 'email',
       'nome@email.com':'nombre@email.com',
       'Digite o seu email!': '¡Introduce tu correo electrónico!',
      'password':'contraseña',
      'Digite a sua senha': 'Escribe tu contraseña',
      'Digite a sua senha!': '¡Escribe tu contraseña!',
      'Digite uma senha mais forte!': '¡Escribe una contraseña más segura!',
       'Esqueceu a Palavra-Passe?': '¿Olvidaste tu contraseña?',
       'Want to create an account?': '¿Quieres crear una cuenta?',
        'Register': "Registro",
        'Produtos': 'Productos',
        'Explore a nossa variedade de produtos': 'Explore nuestra gama de productos',
        'Costumização': 'Personalización',
          'Customize o seu próprio perfil e guarde os seus momentos especiais': 'Personaliza tu propio perfil y guarda tus momentos especiales',
           'Jardim': 'Jardín',
           'Esteja a par do crescimento dos seus alimentos com o nosso menu “Jardim”': 'Mantente en contacto con el crecimiento de tus alimentos con nuestro menú “Jardín”',
             'Next': 'Próximo',
             'Pic Image From': 'Elegir imagen de',
             'CAMERA': 'CÁMARA',
             'GALLERY': 'GALERÍA',
             'CANCEL': 'CANCELAR',
             'O seu Perfil': 'Tu perfil',
              'Adicionar Foto': 'Añadir foto',
              'Nome':'Nombre',
              'Insira o seu nome': 'Escriba su nombre',
              'Digite o seu nome!': '¡Escriba su nombre!',
              'Número Escola (Opcional)': 'Número de escuela (opcional)',
              'Insira o seu número da escola': 'Ingrese su número de escuela'
    }
  };
}